use_frameworks!

platform :ios, '8.0'

target 'JKAliPayHelper_Example' do
  pod 'JKAliPayHelper', :path => '../'

  target 'JKAliPayHelper_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
